from __future__ import annotations

from pathlib import Path

import os
import pytest

if os.getenv("RUN_LEGACY_TWINCAT_TESTS", "0") != "1":
    pytest.skip(
        "Legacy TwinCAT adapter tests are opt-in; set RUN_LEGACY_TWINCAT_TESTS=1",
        allow_module_level=True,
    )


from steuerung3d.adapters.plc_twincat_legacy.udp_sim import build_udp_sim_fleet_from_toml
from steuerung3d.core.command_frame import AxisSetpoint, CommandFrame
from steuerung3d.core.state import MachineState


def _find_repo_root(start: Path) -> Path:
    p = start.resolve()
    for parent in (p, *p.parents):
        if (parent / "pyproject.toml").exists():
            return parent
    raise AssertionError(f"Could not find repo root (pyproject.toml) from {start}")


_DEFAULT_TOML = """    # Auto-generated by test if repo config is missing
[device.plc_twincat_legacy_fleet.defaults]
remote_port = 15001

[[device.plc_twincat_legacy_fleet.axes]]
axis_id = "Anton"
local_port = 51001

[[device.plc_twincat_legacy_fleet.axes]]
axis_id = "Burt"
local_port = 51002

[[device.plc_twincat_legacy_fleet.axes]]
axis_id = "Cecil"
local_port = 51003

[[device.plc_twincat_legacy_fleet.axes]]
axis_id = "Debby"
local_port = 51004
"""


def test_fleet_from_repo_toml_steps_all_axes_and_updates_measured_state(tmp_path: Path):
    repo_root = _find_repo_root(Path(__file__))
    cfg_path = repo_root / "configs" / "dev_plc.toml"

    # Make test self-contained: if the repo doesn't ship configs/dev_plc.toml,
    # generate a temporary one.
    if not cfg_path.exists():
        cfg_path = tmp_path / "dev_plc.toml"
        cfg_path.write_text(_DEFAULT_TOML, encoding="utf-8")

    bundle = build_udp_sim_fleet_from_toml(cfg_path, dt_s=0.01)
    try:
        st = MachineState()

        axis_ids = ["Anton", "Burt", "Cecil", "Debby"]

        for k in range(5):
            cmd = CommandFrame(
                tick=100 + k,
                t_s=0.01 * k,
                estop=False,
                fault=False,
                core_mode="LIVE",
                axes={
                    "Anton": AxisSetpoint(enable=True, vel=0.6),
                    "Burt": AxisSetpoint(enable=True, vel=0.7),
                    "Cecil": AxisSetpoint(enable=True, vel=0.8),
                    "Debby": AxisSetpoint(enable=True, vel=0.9),
                },
            )
            bundle.step(st, cmd, dt=0.01)

        for aid in axis_ids:
            assert aid in st.axes, f"{aid} missing from MachineState.axes"
            ax = st.axes[aid]
            assert ax.pos != 0.0, f"{aid} pos did not change"
            assert ax.vel != 0.0, f"{aid} vel did not change"
            assert ax.enabled is True, f"{aid} not enabled per PLC/SIM report"
    finally:
        bundle.close()
