from typing import Any, Callable, TypeVar, overload

_T = TypeVar("_T")

class BoundSignal:
    def connect(self, slot: Callable[..., object]) -> None: ...
    def emit(self, *args: Any, **kwargs: Any) -> None: ...

class Signal:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, *types: type[Any]) -> None: ...
    def __get__(self, instance: object, owner: type[Any] | None = ...) -> BoundSignal: ...
    def connect(self, slot: Callable[..., object]) -> None: ...
    def emit(self, *args: Any, **kwargs: Any) -> None: ...

class QObject:
    def __init__(self, parent: QObject | None = ...) -> None: ...
    def blockSignals(self, b: bool) -> bool: ...

class QFile:
    ReadOnly: int
    class OpenModeFlag:
        ReadOnly: int
    def __init__(self, name: str = ...) -> None: ...
    def open(self, mode: int) -> bool: ...
    def close(self) -> None: ...
    def fileName(self) -> str: ...

class QLocale:
    RejectGroupSeparator: int
    NumberOption = int
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    @staticmethod
    def c() -> QLocale: ...
    @staticmethod
    def system() -> QLocale: ...
    def setNumberOptions(self, options: int) -> None: ...

class QSize:
    def __init__(self, width: int = ..., height: int = ...) -> None: ...
    def width(self) -> int: ...
    def height(self) -> int: ...

class QPoint:
    def __init__(self, x: int = ..., y: int = ...) -> None: ...
    def x(self) -> int: ...
    def y(self) -> int: ...
    def __add__(self, other: QPoint) -> QPoint: ...

class QRect:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, top_left: QPoint, size: QSize) -> None: ...
    def isNull(self) -> bool: ...
    def isValid(self) -> bool: ...
    def topLeft(self) -> QPoint: ...

class QTimer(QObject):
    timeout: BoundSignal
    def __init__(self, parent: QObject | None = ...) -> None: ...
    def start(self, msec: int = ...) -> None: ...
    def stop(self) -> None: ...
    def setInterval(self, msec: int) -> None: ...
    @staticmethod
    def singleShot(msec: int, func: Callable[[], object]) -> None: ...

class Qt:
    class AlignmentFlag:
        AlignCenter: int
        AlignLeft: int
        AlignRight: int
        AlignVCenter: int
    class Orientation:
        Horizontal: int
        Vertical: int
    class WidgetAttribute:
        WA_TransparentForMouseEvents: int
        WA_ShowWithoutActivating: int
        WA_StyledBackground: int
    class WindowType:
        Tool: int
        FramelessWindowHint: int
        WindowDoesNotAcceptFocus: int
    class MouseButton:
        LeftButton: int
        RightButton: int
