from typing import Any
from .QtCore import QObject

class QColor:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class QFont:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def setPointSize(self, size: int) -> None: ...
    def pointSize(self) -> int: ...
    def setBold(self, bold: bool) -> None: ...

class QDoubleValidator(QObject):
    class Notation:
        StandardNotation: int
        ScientificNotation: int
    StandardNotation: int
    ScientificNotation: int
    def __init__(self, bottom: float = ..., top: float = ..., decimals: int = ..., parent: QObject | None = ...) -> None: ...
    def setLocale(self, locale: object) -> None: ...
    def setNotation(self, notation: int) -> None: ...
    def setDecimals(self, decimals: int) -> None: ...
    def setBottom(self, value: float) -> None: ...
    def setTop(self, value: float) -> None: ...

class QPen:
    def __init__(self, color: QColor | None = ..., width: int = ...) -> None: ...

class QPainter:
    class RenderHint:
        Antialiasing: int
    Antialiasing: int
    def __init__(self, device: object | None = ...) -> None: ...
    def setRenderHint(self, hint: int, on: bool = ...) -> None: ...
    def font(self) -> QFont: ...
    def setFont(self, font: QFont) -> None: ...
    def setPen(self, pen: QPen | QColor) -> None: ...
    def setBrush(self, brush: QColor) -> None: ...
    def drawEllipse(self, *args: Any) -> None: ...
    def drawLine(self, *args: Any) -> None: ...
    def drawText(self, *args: Any) -> None: ...
    def end(self) -> None: ...
