from typing import Any, Iterable, TypeVar, overload
_T = TypeVar("_T", bound=object)
from .QtCore import BoundSignal, QObject, QPoint, QSize
from .QtGui import QFont, QDoubleValidator

class QApplication(QObject):
    aboutToQuit: BoundSignal
    def __init__(self, args: list[str] | None = ...) -> None: ...
    def exec(self) -> int: ...
    @staticmethod
    def instance() -> QApplication | None: ...
    def quit(self) -> None: ...
    def setFont(self, font: QFont) -> None: ...

class QWidget(QObject):
    @overload
    def __init__(self, parent: QWidget | None = ...) -> None: ...
    @overload
    def __init__(self, parent: QWidget | None, f: int) -> None: ...
    def show(self) -> None: ...
    def setWindowTitle(self, title: str) -> None: ...
    def window(self) -> QWidget: ...
    def adjustSize(self) -> None: ...
    def width(self) -> int: ...
    def height(self) -> int: ...
    def setFixedWidth(self, width: int) -> None: ...
    def minimumSizeHint(self) -> QSize: ...
    def sizeHint(self) -> QSize: ...
    def toolTip(self) -> str: ...
    def setProperty(self, name: str, value: object) -> bool: ...
    def isVisible(self) -> bool: ...
    def hide(self) -> None: ...
    def close(self) -> bool: ...
    def setVisible(self, visible: bool) -> None: ...
    def setEnabled(self, enabled: bool) -> None: ...
    def setDisabled(self, disabled: bool) -> None: ...
    def isEnabled(self) -> bool: ...
    def setToolTip(self, text: str) -> None: ...
    def setStyleSheet(self, style: str) -> None: ...
    def setContentsMargins(self, left: int, top: int, right: int, bottom: int) -> None: ...
    def setLayout(self, layout: object) -> None: ...
    def layout(self) -> object | None: ...
    def parentWidget(self) -> QWidget | None: ...
    def findChild(self, type: type[_T], name: str = ...) -> _T | None: ...
    def findChildren(self, type: type[_T]) -> list[_T]: ...
    def objectName(self) -> str: ...
    def setObjectName(self, name: str) -> None: ...
    def resize(self, width: int, height: int) -> None: ...
    def move(self, point: QPoint) -> None: ...
    def size(self) -> QSize: ...
    def mapToGlobal(self, point: QPoint) -> QPoint: ...
    def raise_(self) -> None: ...
    @overload
    def setMinimumSize(self, size: QSize) -> None: ...
    @overload
    def setMinimumSize(self, width: int, height: int) -> None: ...
    def setMinimumHeight(self, h: int) -> None: ...
    def setMaximumHeight(self, h: int) -> None: ...
    def setSizePolicy(self, horizontal: int, vertical: int) -> None: ...
    def update(self) -> None: ...
    def repaint(self) -> None: ...
    def font(self) -> QFont: ...
    def setFont(self, font: QFont) -> None: ...
    def setAttribute(self, attr: int, on: bool = ...) -> None: ...

class QFrame(QWidget):
    class Shape:
        StyledPanel: int
        HLine: int
    class Shadow:
        Sunken: int
    def setFrameShape(self, shape: int) -> None: ...
    def setFrameShadow(self, shadow: int) -> None: ...


class QLabel(QWidget):
    def __init__(self, text: str = ..., parent: QWidget | None = ...) -> None: ...
    def setText(self, text: str) -> None: ...
    def text(self) -> str: ...
    def setAlignment(self, alignment: int) -> None: ...

class QMainWindow(QWidget):
    def setCentralWidget(self, widget: QWidget) -> None: ...

class QMessageBox:
    @staticmethod
    def information(parent: QWidget | None, title: str, text: str) -> int: ...

class QAbstractButton(QWidget):
    clicked: BoundSignal
    toggled: BoundSignal
    pressed: BoundSignal
    released: BoundSignal
    def setText(self, text: str) -> None: ...
    def text(self) -> str: ...
    def setCheckable(self, value: bool) -> None: ...
    def setChecked(self, value: bool) -> None: ...
    def isChecked(self) -> bool: ...

class QPushButton(QAbstractButton):
    def __init__(self, text: str = ..., parent: QWidget | None = ...) -> None: ...

class QCheckBox(QAbstractButton):
    stateChanged: BoundSignal
    def __init__(self, text: str = ..., parent: QWidget | None = ...) -> None: ...

class QLineEdit(QWidget):
    editingFinished: BoundSignal
    textChanged: BoundSignal
    returnPressed: BoundSignal
    def __init__(self, text: str = ..., parent: QWidget | None = ...) -> None: ...
    def setText(self, text: str) -> None: ...
    def text(self) -> str: ...
    def clear(self) -> None: ...
    def setAlignment(self, alignment: int) -> None: ...
    def setReadOnly(self, value: bool) -> None: ...
    def setPlaceholderText(self, text: str) -> None: ...
    def setValidator(self, validator: QDoubleValidator | None) -> None: ...

class QComboBox(QWidget):
    currentTextChanged: BoundSignal
    currentIndexChanged: BoundSignal
    activated: BoundSignal
    def __init__(self, parent: QWidget | None = ...) -> None: ...
    def addItem(self, text: str, userData: object | None = ...) -> None: ...
    def addItems(self, texts: Iterable[str]) -> None: ...
    def clear(self) -> None: ...
    def setAlignment(self, alignment: int) -> None: ...
    def currentText(self) -> str: ...
    def setCurrentText(self, text: str) -> None: ...
    def setCurrentIndex(self, index: int) -> None: ...
    def currentIndex(self) -> int: ...
    def count(self) -> int: ...
    def itemText(self, index: int) -> str: ...
    def itemData(self, index: int) -> object | None: ...
    def setItemText(self, index: int, text: str) -> None: ...

class QAbstractSlider(QWidget):
    valueChanged: BoundSignal
    sliderMoved: BoundSignal
    actionTriggered: BoundSignal
    def setRange(self, min_value: int, max_value: int) -> None: ...
    def setValue(self, value: int) -> None: ...
    def value(self) -> int: ...
    def setSingleStep(self, step: int) -> None: ...
    def setPageStep(self, step: int) -> None: ...

class QSlider(QAbstractSlider):
    def __init__(self, orientation: int, parent: QWidget | None = ...) -> None: ...

class QSpinBox(QWidget):
    valueChanged: BoundSignal
    def setRange(self, min_value: int, max_value: int) -> None: ...
    def setValue(self, value: int) -> None: ...
    def value(self) -> int: ...

class QDoubleSpinBox(QWidget):
    valueChanged: BoundSignal
    def setRange(self, min_value: float, max_value: float) -> None: ...
    def setValue(self, value: float) -> None: ...
    def value(self) -> float: ...
    def setDecimals(self, value: int) -> None: ...

class QGroupBox(QWidget):
    def __init__(self, title: str = ..., parent: QWidget | None = ...) -> None: ...

class _TabBar(QWidget):
    def setVisible(self, visible: bool) -> None: ...
    def setEnabled(self, enabled: bool) -> None: ...

class QTabWidget(QWidget):
    def currentIndex(self) -> int: ...
    def setCurrentIndex(self, index: int) -> None: ...
    def tabBar(self) -> _TabBar: ...
    def indexOf(self, widget: QWidget) -> int: ...
    def setTabVisible(self, index: int, visible: bool) -> None: ...
    def setTabEnabled(self, index: int, enabled: bool) -> None: ...

class QSpacerItem:
    def __init__(self, w: int, h: int, *args: Any, **kwargs: Any) -> None: ...

class QSizePolicy:
    class Policy:
        Expanding: int
        Preferred: int
        Minimum: int
        Fixed: int
    Expanding: int
    Preferred: int
    Minimum: int
    Fixed: int

class _BaseLayout(QObject):
    def addWidget(self, widget: QWidget, *args: Any) -> None: ...
    def addLayout(self, layout: _BaseLayout, *args: Any) -> None: ...
    def addStretch(self, stretch: int = ...) -> None: ...
    def addItem(self, item: QSpacerItem) -> None: ...
    def setContentsMargins(self, left: int, top: int, right: int, bottom: int) -> None: ...
    def setSpacing(self, spacing: int) -> None: ...
    def setAlignment(self, *args: Any) -> None: ...

class QHBoxLayout(_BaseLayout):
    def __init__(self, parent: QWidget | None = ...) -> None: ...

class QVBoxLayout(_BaseLayout):
    def __init__(self, parent: QWidget | None = ...) -> None: ...

class QGridLayout(_BaseLayout):
    def __init__(self, parent: QWidget | None = ...) -> None: ...
    def setHorizontalSpacing(self, spacing: int) -> None: ...
    def setVerticalSpacing(self, spacing: int) -> None: ...

class QHeaderView:
    def setDefaultSectionSize(self, size: int) -> None: ...

class QTableWidgetItem:
    def __init__(self, text: str = ...) -> None: ...
    def setText(self, text: str) -> None: ...
    def text(self) -> str: ...
    def setTextAlignment(self, alignment: int) -> None: ...

class QTableWidget(QWidget):
    def __init__(self, rows: int = ..., columns: int = ..., parent: QWidget | None = ...) -> None: ...
    def setHorizontalHeaderLabels(self, labels: Iterable[str]) -> None: ...
    def setColumnWidth(self, column: int, width: int) -> None: ...
    def setRowHeight(self, row: int, height: int) -> None: ...
    def setRowCount(self, rows: int) -> None: ...
    def rowCount(self) -> int: ...
    def removeRow(self, row: int) -> None: ...
    def item(self, row: int, column: int) -> QTableWidgetItem | None: ...
    def setItem(self, row: int, column: int, item: QTableWidgetItem) -> None: ...
    def cellWidget(self, row: int, column: int) -> QWidget | None: ...
    def setCellWidget(self, row: int, column: int, widget: QWidget) -> None: ...
    def verticalHeader(self) -> QHeaderView: ...
