# Minimal config used by tests (TwinCAT legacy UDP fleet SIM)
[device.plc_twincat_legacy_fleet.defaults]
remote_port = 15001

[[device.plc_twincat_legacy_fleet.axes]]
axis_id = "Anton"
local_port = 51001

[[device.plc_twincat_legacy_fleet.axes]]
axis_id = "Burt"
local_port = 51002

[[device.plc_twincat_legacy_fleet.axes]]
axis_id = "Cecil"
local_port = 51003

[[device.plc_twincat_legacy_fleet.axes]]
axis_id = "Debby"
local_port = 51004
